api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

# FROM DAVID :  I have decided to not change the layout of the API but ultimately,
#               a company would like to have its own layout in order to look professional
#               towards their clients